TEXT_SCORE = "SCORE";
TEXT_GAME_OVER = "GAME OVER";
TEXT_JUMP = "JUMP";
TEXT_PLAY = "PLAY";
TEXT_HELP1 = "AVOID THE OPPOSING \nCARS CLICKING THE ARROWS\n OR THE JUMP BUTTON";
TEXT_HELP2 = "TRY TO DRIVE\n AS LONG AS POSSIBLE";